### ISSUE TITLE
Storage is empty after restart app, after update to expo SDK 35

### ISSUE THREAD

**Issue by UchihaVeha** [t73liu/redux-persist-expo-filesystem#3]
The store is empty after every restart app on android in the standalone build. In dev mode, all work fine

**Comment by t73liu** [comment]
The directory path has not changed with with recent Expo updates (33 to 35).
```javascript
import * as FileSystem from "expo-file-system";
console.log(FileSystem.documentDirectory);
// Prints the following on Android (Pixel 3):
// 'file:///data/user/0/host.exp.exponent/files/ExperienceData/@user/project-slug/....'
```
Note if you changed the `app.json` slug property, the path will be different. Similarly, if your username has changed recently.

**Comment by UchihaVeha** [comment]
I do not change slug or username, just update to SDK 35, also its happen only in standalone build, in dev work fine

**Comment by t73liu** [comment]
It sounds similar to the following issue https://github.com/expo/expo/issues/4537
