### ISSUE TITLE
The method or property expo-file-system.getInfoAsync is not available on web, are you sure you've linked all the native dependencies properly?

### ISSUE THREAD

**Issue by tabaktoni** [t73liu/redux-persist-expo-filesystem#5]
The method or property expo-file-system.getInfoAsync is not available on web, are you sure you've linked all the native dependencies properly?

Is this working with expo web app build?

**Comment by t73liu** [comment]
According to the Expo docs, `expo-file-system` does not support web: https://docs.expo.io/versions/latest/sdk/filesystem/
